name: Print a single environment variable

on:

  push:
    branches:
      - main

jobs:
  print-environment-variable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Environment Variable
        run: echo "NAME=Mateo" >> $GITHUB_ENV

      - name: Print Environment Variable
        run: echo Hello, $NAME!
